title: Linkk status page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Website
      description: Our company public facing website
      link: https://linkk.me/
    - name: Helpdesk
      description: Our company customer support site
      link: https://ec.linkk.me/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: ""
  copyrightHolder: Linkk.
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit Linkk.me'
    href='https://linkk.me/'>Linkk</a> provides open-source software for all
    kind of sectors.
